version: '3'

services:
    lufi:
        image: 'sbellon/lufi'
        build: .
        restart: unless-stopped
        ports:
            - "${LUFI_PORT}:8081"
        environment:
            - INSTANCE_NAME=${LUFI_INSTANCE_NAME}
            - CONTACT=${LUFI_CONTACT}
            - REPORT=${LUFI_REPORT}
            - MAIL_HOST=${LUFI_MAIL_HOST}
            - MAIL_SENDER=${LUFI_MAIL_SENDER}
            - DEFAULT_DELAY=${LUFI_DEFAULT_DELAY}
            - MAX_FILE_SIZE=${LUFI_MAX_FILE_SIZE}
            - MAX_TOTAL_SIZE=${LUFI_MAX_TOTAL_SIZE}
        volumes:
            - ${LUFI_HOST_DIR}/data:/usr/lufi/data
            - ${LUFI_HOST_DIR}/files:/usr/lufi/files

